### ISSUE TITLE
Research creative studio/portfolio sites

### ISSUE THREAD

**Issue by NextCheckbox** [NextCheckbox/NextCheckbox.com#1]
## Scope
- [ ] I have a collection of sites to be inspired by
- [ ] I understand the services offered by creative studios
- [ ] I have an idea of what services I'd like to offer myself

## Tasks
- [ ] Research a list of creative code studios and their websites
